// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAIModel(arg1) {
  return window['go']['main']['App']['CreateAIModel'](arg1);
}

export function CreateAgent(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['CreateAgent'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function CreateMCPServer(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['CreateMCPServer'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function CreateProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2, arg3);
}

export function CreateSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateSession'](arg1, arg2, arg3);
}

export function CreateTool(arg1) {
  return window['go']['main']['App']['CreateTool'](arg1);
}

export function DeleteAIModel(arg1) {
  return window['go']['main']['App']['DeleteAIModel'](arg1);
}

export function DeleteAgent(arg1) {
  return window['go']['main']['App']['DeleteAgent'](arg1);
}

export function DeleteMCPServer(arg1) {
  return window['go']['main']['App']['DeleteMCPServer'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function DeleteTool(arg1) {
  return window['go']['main']['App']['DeleteTool'](arg1);
}

export function GetScriptAPIDocs() {
  return window['go']['main']['App']['GetScriptAPIDocs']();
}

export function GetSessionMessages(arg1) {
  return window['go']['main']['App']['GetSessionMessages'](arg1);
}

export function IndexAllProjects() {
  return window['go']['main']['App']['IndexAllProjects']();
}

export function IndexProject(arg1) {
  return window['go']['main']['App']['IndexProject'](arg1);
}

export function ListAIModels() {
  return window['go']['main']['App']['ListAIModels']();
}

export function ListAgents() {
  return window['go']['main']['App']['ListAgents']();
}

export function ListMCPServers() {
  return window['go']['main']['App']['ListMCPServers']();
}

export function ListMCPTools(arg1) {
  return window['go']['main']['App']['ListMCPTools'](arg1);
}

export function ListModes() {
  return window['go']['main']['App']['ListModes']();
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ListSessions(arg1) {
  return window['go']['main']['App']['ListSessions'](arg1);
}

export function ListTools() {
  return window['go']['main']['App']['ListTools']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function TestAIModel(arg1) {
  return window['go']['main']['App']['TestAIModel'](arg1);
}

export function UpdateAgent(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['UpdateAgent'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function UpdateMCPServer(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['UpdateMCPServer'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function UpdateProject(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateProject'](arg1, arg2, arg3, arg4);
}

export function UpdateSession(arg1, arg2) {
  return window['go']['main']['App']['UpdateSession'](arg1, arg2);
}

export function UpdateTool(arg1) {
  return window['go']['main']['App']['UpdateTool'](arg1);
}
