// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.1
// source: api/proto/service.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	model "iat/pkg/pb/model"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_proto_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_proto_service_proto_rawDescGZIP(), []int{0}
}

type IDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDRequest) Reset() {
	*x = IDRequest{}
	mi := &file_api_proto_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDRequest) ProtoMessage() {}

func (x *IDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDRequest.ProtoReflect.Descriptor instead.
func (*IDRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_service_proto_rawDescGZIP(), []int{1}
}

func (x *IDRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectRequest) Reset() {
	*x = CreateProjectRequest{}
	mi := &file_api_proto_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectRequest) ProtoMessage() {}

func (x *CreateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectRequest.ProtoReflect.Descriptor instead.
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProjectRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProjectRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type UpdateProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProjectRequest) Reset() {
	*x = UpdateProjectRequest{}
	mi := &file_api_proto_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProjectRequest) ProtoMessage() {}

func (x *UpdateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProjectRequest.ProtoReflect.Descriptor instead.
func (*UpdateProjectRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_service_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateProjectRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProjectRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateProjectRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ListProjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*model.Project       `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsResponse) Reset() {
	*x = ListProjectsResponse{}
	mi := &file_api_proto_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsResponse) ProtoMessage() {}

func (x *ListProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsResponse.ProtoReflect.Descriptor instead.
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListProjectsResponse) GetProjects() []*model.Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     uint32                 `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserMessage   string                 `protobuf:"bytes,2,opt,name=user_message,json=userMessage,proto3" json:"user_message,omitempty"`
	AgentId       uint32                 `protobuf:"varint,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Mode          string                 `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_api_proto_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_service_proto_rawDescGZIP(), []int{5}
}

func (x *ChatRequest) GetSessionId() uint32 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *ChatRequest) GetUserMessage() string {
	if x != nil {
		return x.UserMessage
	}
	return ""
}

func (x *ChatRequest) GetAgentId() uint32 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *ChatRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type ChatEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`       // "chunk", "tool_start", "tool_end", "error", "done"
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // for chunk/error
	Extra         string                 `protobuf:"bytes,3,opt,name=extra,proto3" json:"extra,omitempty"`     // JSON for tool details etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatEvent) Reset() {
	*x = ChatEvent{}
	mi := &file_api_proto_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatEvent) ProtoMessage() {}

func (x *ChatEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatEvent.ProtoReflect.Descriptor instead.
func (*ChatEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_service_proto_rawDescGZIP(), []int{6}
}

func (x *ChatEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ChatEvent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatEvent) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

type ListMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*model.Message       `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesResponse) Reset() {
	*x = ListMessagesResponse{}
	mi := &file_api_proto_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesResponse) ProtoMessage() {}

func (x *ListMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesResponse.ProtoReflect.Descriptor instead.
func (*ListMessagesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListMessagesResponse) GetMessages() []*model.Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     uint32                 `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AgentId       uint32                 `protobuf:"varint,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_api_proto_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_service_proto_rawDescGZIP(), []int{8}
}

func (x *CreateSessionRequest) GetProjectId() uint32 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *CreateSessionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSessionRequest) GetAgentId() uint32 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*model.Session       `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_api_proto_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_service_proto_rawDescGZIP(), []int{9}
}

func (x *ListSessionsResponse) GetSessions() []*model.Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     uint32                 `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Priority      string                 `protobuf:"bytes,3,opt,name=priority,proto3" json:"priority,omitempty"`
	ParentId      uint32                 `protobuf:"varint,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"` // 0 if none
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_api_proto_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_service_proto_rawDescGZIP(), []int{10}
}

func (x *CreateTaskRequest) GetSessionId() uint32 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *CreateTaskRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateTaskRequest) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *CreateTaskRequest) GetParentId() uint32 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

type UpdateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskRequest) Reset() {
	*x = UpdateTaskRequest{}
	mi := &file_api_proto_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskRequest) ProtoMessage() {}

func (x *UpdateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_service_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateTaskRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTaskRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*model.Task          `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_api_proto_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_service_proto_rawDescGZIP(), []int{12}
}

func (x *ListTasksResponse) GetTasks() []*model.Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type CreateAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	SystemPrompt  string                 `protobuf:"bytes,3,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	ModelId       uint32                 `protobuf:"varint,4,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	ToolIds       []uint32               `protobuf:"varint,5,rep,packed,name=tool_ids,json=toolIds,proto3" json:"tool_ids,omitempty"`
	McpServerIds  []uint32               `protobuf:"varint,6,rep,packed,name=mcp_server_ids,json=mcpServerIds,proto3" json:"mcp_server_ids,omitempty"`
	ModeId        uint32                 `protobuf:"varint,7,opt,name=mode_id,json=modeId,proto3" json:"mode_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAgentRequest) Reset() {
	*x = CreateAgentRequest{}
	mi := &file_api_proto_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAgentRequest) ProtoMessage() {}

func (x *CreateAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAgentRequest.ProtoReflect.Descriptor instead.
func (*CreateAgentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_service_proto_rawDescGZIP(), []int{13}
}

func (x *CreateAgentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAgentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateAgentRequest) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *CreateAgentRequest) GetModelId() uint32 {
	if x != nil {
		return x.ModelId
	}
	return 0
}

func (x *CreateAgentRequest) GetToolIds() []uint32 {
	if x != nil {
		return x.ToolIds
	}
	return nil
}

func (x *CreateAgentRequest) GetMcpServerIds() []uint32 {
	if x != nil {
		return x.McpServerIds
	}
	return nil
}

func (x *CreateAgentRequest) GetModeId() uint32 {
	if x != nil {
		return x.ModeId
	}
	return 0
}

type UpdateAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	SystemPrompt  string                 `protobuf:"bytes,4,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	ModelId       uint32                 `protobuf:"varint,5,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	ToolIds       []uint32               `protobuf:"varint,6,rep,packed,name=tool_ids,json=toolIds,proto3" json:"tool_ids,omitempty"`
	McpServerIds  []uint32               `protobuf:"varint,7,rep,packed,name=mcp_server_ids,json=mcpServerIds,proto3" json:"mcp_server_ids,omitempty"`
	ModeId        uint32                 `protobuf:"varint,8,opt,name=mode_id,json=modeId,proto3" json:"mode_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAgentRequest) Reset() {
	*x = UpdateAgentRequest{}
	mi := &file_api_proto_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAgentRequest) ProtoMessage() {}

func (x *UpdateAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAgentRequest.ProtoReflect.Descriptor instead.
func (*UpdateAgentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_service_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateAgentRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateAgentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateAgentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateAgentRequest) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *UpdateAgentRequest) GetModelId() uint32 {
	if x != nil {
		return x.ModelId
	}
	return 0
}

func (x *UpdateAgentRequest) GetToolIds() []uint32 {
	if x != nil {
		return x.ToolIds
	}
	return nil
}

func (x *UpdateAgentRequest) GetMcpServerIds() []uint32 {
	if x != nil {
		return x.McpServerIds
	}
	return nil
}

func (x *UpdateAgentRequest) GetModeId() uint32 {
	if x != nil {
		return x.ModeId
	}
	return 0
}

type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*model.Agent         `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_api_proto_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_service_proto_rawDescGZIP(), []int{15}
}

func (x *ListAgentsResponse) GetAgents() []*model.Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

type CreateMCPServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Command       string                 `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	Args          string                 `protobuf:"bytes,5,opt,name=args,proto3" json:"args,omitempty"`
	Env           string                 `protobuf:"bytes,6,opt,name=env,proto3" json:"env,omitempty"`
	Url           string                 `protobuf:"bytes,7,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMCPServerRequest) Reset() {
	*x = CreateMCPServerRequest{}
	mi := &file_api_proto_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMCPServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMCPServerRequest) ProtoMessage() {}

func (x *CreateMCPServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMCPServerRequest.ProtoReflect.Descriptor instead.
func (*CreateMCPServerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_service_proto_rawDescGZIP(), []int{16}
}

func (x *CreateMCPServerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateMCPServerRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateMCPServerRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateMCPServerRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CreateMCPServerRequest) GetArgs() string {
	if x != nil {
		return x.Args
	}
	return ""
}

func (x *CreateMCPServerRequest) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *CreateMCPServerRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type UpdateMCPServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Command       string                 `protobuf:"bytes,5,opt,name=command,proto3" json:"command,omitempty"`
	Args          string                 `protobuf:"bytes,6,opt,name=args,proto3" json:"args,omitempty"`
	Env           string                 `protobuf:"bytes,7,opt,name=env,proto3" json:"env,omitempty"`
	Url           string                 `protobuf:"bytes,8,opt,name=url,proto3" json:"url,omitempty"`
	Enabled       bool                   `protobuf:"varint,9,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMCPServerRequest) Reset() {
	*x = UpdateMCPServerRequest{}
	mi := &file_api_proto_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMCPServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMCPServerRequest) ProtoMessage() {}

func (x *UpdateMCPServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMCPServerRequest.ProtoReflect.Descriptor instead.
func (*UpdateMCPServerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_service_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateMCPServerRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateMCPServerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateMCPServerRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateMCPServerRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateMCPServerRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *UpdateMCPServerRequest) GetArgs() string {
	if x != nil {
		return x.Args
	}
	return ""
}

func (x *UpdateMCPServerRequest) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *UpdateMCPServerRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UpdateMCPServerRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type ListMCPServersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Servers       []*model.MCPServer     `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMCPServersResponse) Reset() {
	*x = ListMCPServersResponse{}
	mi := &file_api_proto_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMCPServersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMCPServersResponse) ProtoMessage() {}

func (x *ListMCPServersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMCPServersResponse.ProtoReflect.Descriptor instead.
func (*ListMCPServersResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_service_proto_rawDescGZIP(), []int{18}
}

func (x *ListMCPServersResponse) GetServers() []*model.MCPServer {
	if x != nil {
		return x.Servers
	}
	return nil
}

type ListMCPToolsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tools         []*ToolInfo            `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMCPToolsResponse) Reset() {
	*x = ListMCPToolsResponse{}
	mi := &file_api_proto_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMCPToolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMCPToolsResponse) ProtoMessage() {}

func (x *ListMCPToolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMCPToolsResponse.ProtoReflect.Descriptor instead.
func (*ListMCPToolsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_service_proto_rawDescGZIP(), []int{19}
}

func (x *ListMCPToolsResponse) GetTools() []*ToolInfo {
	if x != nil {
		return x.Tools
	}
	return nil
}

type ToolInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Desc  string                 `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	// Schema is complex, maybe just return JSON string
	SchemaJson    string `protobuf:"bytes,3,opt,name=schema_json,json=schemaJson,proto3" json:"schema_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolInfo) Reset() {
	*x = ToolInfo{}
	mi := &file_api_proto_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolInfo) ProtoMessage() {}

func (x *ToolInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolInfo.ProtoReflect.Descriptor instead.
func (*ToolInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_service_proto_rawDescGZIP(), []int{20}
}

func (x *ToolInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolInfo) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *ToolInfo) GetSchemaJson() string {
	if x != nil {
		return x.SchemaJson
	}
	return ""
}

var File_api_proto_service_proto protoreflect.FileDescriptor

const file_api_proto_service_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/service.proto\x12\aservice\x1a\x15api/proto/model.proto\"\a\n" +
	"\x05Empty\"\x1b\n" +
	"\tIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"`\n" +
	"\x14CreateProjectRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\"p\n" +
	"\x14UpdateProjectRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\"B\n" +
	"\x14ListProjectsResponse\x12*\n" +
	"\bprojects\x18\x01 \x03(\v2\x0e.model.ProjectR\bprojects\"~\n" +
	"\vChatRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\rR\tsessionId\x12!\n" +
	"\fuser_message\x18\x02 \x01(\tR\vuserMessage\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\rR\aagentId\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\tR\x04mode\"O\n" +
	"\tChatEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x14\n" +
	"\x05extra\x18\x03 \x01(\tR\x05extra\"B\n" +
	"\x14ListMessagesResponse\x12*\n" +
	"\bmessages\x18\x01 \x03(\v2\x0e.model.MessageR\bmessages\"d\n" +
	"\x14CreateSessionRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\rR\tprojectId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\rR\aagentId\"B\n" +
	"\x14ListSessionsResponse\x12*\n" +
	"\bsessions\x18\x01 \x03(\v2\x0e.model.SessionR\bsessions\"\x85\x01\n" +
	"\x11CreateTaskRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\rR\tsessionId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\tR\bpriority\x12\x1b\n" +
	"\tparent_id\x18\x04 \x01(\rR\bparentId\";\n" +
	"\x11UpdateTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"6\n" +
	"\x11ListTasksResponse\x12!\n" +
	"\x05tasks\x18\x01 \x03(\v2\v.model.TaskR\x05tasks\"\xe4\x01\n" +
	"\x12CreateAgentRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12#\n" +
	"\rsystem_prompt\x18\x03 \x01(\tR\fsystemPrompt\x12\x19\n" +
	"\bmodel_id\x18\x04 \x01(\rR\amodelId\x12\x19\n" +
	"\btool_ids\x18\x05 \x03(\rR\atoolIds\x12$\n" +
	"\x0emcp_server_ids\x18\x06 \x03(\rR\fmcpServerIds\x12\x17\n" +
	"\amode_id\x18\a \x01(\rR\x06modeId\"\xf4\x01\n" +
	"\x12UpdateAgentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12#\n" +
	"\rsystem_prompt\x18\x04 \x01(\tR\fsystemPrompt\x12\x19\n" +
	"\bmodel_id\x18\x05 \x01(\rR\amodelId\x12\x19\n" +
	"\btool_ids\x18\x06 \x03(\rR\atoolIds\x12$\n" +
	"\x0emcp_server_ids\x18\a \x03(\rR\fmcpServerIds\x12\x17\n" +
	"\amode_id\x18\b \x01(\rR\x06modeId\":\n" +
	"\x12ListAgentsResponse\x12$\n" +
	"\x06agents\x18\x01 \x03(\v2\f.model.AgentR\x06agents\"\xb4\x01\n" +
	"\x16CreateMCPServerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\acommand\x18\x04 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x05 \x01(\tR\x04args\x12\x10\n" +
	"\x03env\x18\x06 \x01(\tR\x03env\x12\x10\n" +
	"\x03url\x18\a \x01(\tR\x03url\"\xde\x01\n" +
	"\x16UpdateMCPServerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x18\n" +
	"\acommand\x18\x05 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x06 \x01(\tR\x04args\x12\x10\n" +
	"\x03env\x18\a \x01(\tR\x03env\x12\x10\n" +
	"\x03url\x18\b \x01(\tR\x03url\x12\x18\n" +
	"\aenabled\x18\t \x01(\bR\aenabled\"D\n" +
	"\x16ListMCPServersResponse\x12*\n" +
	"\aservers\x18\x01 \x03(\v2\x10.model.MCPServerR\aservers\"?\n" +
	"\x14ListMCPToolsResponse\x12'\n" +
	"\x05tools\x18\x01 \x03(\v2\x11.service.ToolInfoR\x05tools\"S\n" +
	"\bToolInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04desc\x18\x02 \x01(\tR\x04desc\x12\x1f\n" +
	"\vschema_json\x18\x03 \x01(\tR\n" +
	"schemaJson2\xb0\x02\n" +
	"\x0eProjectService\x12;\n" +
	"\rCreateProject\x12\x1d.service.CreateProjectRequest\x1a\v.model.Base\x12;\n" +
	"\rUpdateProject\x12\x1d.service.UpdateProjectRequest\x1a\v.model.Base\x123\n" +
	"\rDeleteProject\x12\x12.service.IDRequest\x1a\x0e.service.Empty\x12=\n" +
	"\fListProjects\x12\x0e.service.Empty\x1a\x1d.service.ListProjectsResponse\x120\n" +
	"\n" +
	"GetProject\x12\x12.service.IDRequest\x1a\x0e.model.Project2\xee\x02\n" +
	"\vChatService\x122\n" +
	"\x04Chat\x12\x14.service.ChatRequest\x1a\x12.service.ChatEvent0\x01\x12A\n" +
	"\fListMessages\x12\x12.service.IDRequest\x1a\x1d.service.ListMessagesResponse\x123\n" +
	"\rClearMessages\x12\x12.service.IDRequest\x1a\x0e.service.Empty\x12;\n" +
	"\rCreateSession\x12\x1d.service.CreateSessionRequest\x1a\v.model.Base\x12A\n" +
	"\fListSessions\x12\x12.service.IDRequest\x1a\x1d.service.ListSessionsResponse\x123\n" +
	"\rDeleteSession\x12\x12.service.IDRequest\x1a\x0e.service.Empty2\xed\x01\n" +
	"\vTaskService\x125\n" +
	"\n" +
	"CreateTask\x12\x1a.service.CreateTaskRequest\x1a\v.model.Task\x128\n" +
	"\n" +
	"UpdateTask\x12\x1a.service.UpdateTaskRequest\x1a\x0e.service.Empty\x120\n" +
	"\n" +
	"DeleteTask\x12\x12.service.IDRequest\x1a\x0e.service.Empty\x12;\n" +
	"\tListTasks\x12\x12.service.IDRequest\x1a\x1a.service.ListTasksResponse2\xee\x01\n" +
	"\fAgentService\x127\n" +
	"\vCreateAgent\x12\x1b.service.CreateAgentRequest\x1a\v.model.Base\x127\n" +
	"\vUpdateAgent\x12\x1b.service.UpdateAgentRequest\x1a\v.model.Base\x121\n" +
	"\vDeleteAgent\x12\x12.service.IDRequest\x1a\x0e.service.Empty\x129\n" +
	"\n" +
	"ListAgents\x12\x0e.service.Empty\x1a\x1b.service.ListAgentsResponse2\xcb\x02\n" +
	"\n" +
	"MCPService\x12?\n" +
	"\x0fCreateMCPServer\x12\x1f.service.CreateMCPServerRequest\x1a\v.model.Base\x12?\n" +
	"\x0fUpdateMCPServer\x12\x1f.service.UpdateMCPServerRequest\x1a\v.model.Base\x125\n" +
	"\x0fDeleteMCPServer\x12\x12.service.IDRequest\x1a\x0e.service.Empty\x12A\n" +
	"\x0eListMCPServers\x12\x0e.service.Empty\x1a\x1f.service.ListMCPServersResponse\x12A\n" +
	"\fListMCPTools\x12\x12.service.IDRequest\x1a\x1d.service.ListMCPToolsResponseB\x14Z\x12iat/pkg/pb/serviceb\x06proto3"

var (
	file_api_proto_service_proto_rawDescOnce sync.Once
	file_api_proto_service_proto_rawDescData []byte
)

func file_api_proto_service_proto_rawDescGZIP() []byte {
	file_api_proto_service_proto_rawDescOnce.Do(func() {
		file_api_proto_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_service_proto_rawDesc), len(file_api_proto_service_proto_rawDesc)))
	})
	return file_api_proto_service_proto_rawDescData
}

var file_api_proto_service_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_api_proto_service_proto_goTypes = []any{
	(*Empty)(nil),                  // 0: service.Empty
	(*IDRequest)(nil),              // 1: service.IDRequest
	(*CreateProjectRequest)(nil),   // 2: service.CreateProjectRequest
	(*UpdateProjectRequest)(nil),   // 3: service.UpdateProjectRequest
	(*ListProjectsResponse)(nil),   // 4: service.ListProjectsResponse
	(*ChatRequest)(nil),            // 5: service.ChatRequest
	(*ChatEvent)(nil),              // 6: service.ChatEvent
	(*ListMessagesResponse)(nil),   // 7: service.ListMessagesResponse
	(*CreateSessionRequest)(nil),   // 8: service.CreateSessionRequest
	(*ListSessionsResponse)(nil),   // 9: service.ListSessionsResponse
	(*CreateTaskRequest)(nil),      // 10: service.CreateTaskRequest
	(*UpdateTaskRequest)(nil),      // 11: service.UpdateTaskRequest
	(*ListTasksResponse)(nil),      // 12: service.ListTasksResponse
	(*CreateAgentRequest)(nil),     // 13: service.CreateAgentRequest
	(*UpdateAgentRequest)(nil),     // 14: service.UpdateAgentRequest
	(*ListAgentsResponse)(nil),     // 15: service.ListAgentsResponse
	(*CreateMCPServerRequest)(nil), // 16: service.CreateMCPServerRequest
	(*UpdateMCPServerRequest)(nil), // 17: service.UpdateMCPServerRequest
	(*ListMCPServersResponse)(nil), // 18: service.ListMCPServersResponse
	(*ListMCPToolsResponse)(nil),   // 19: service.ListMCPToolsResponse
	(*ToolInfo)(nil),               // 20: service.ToolInfo
	(*model.Project)(nil),          // 21: model.Project
	(*model.Message)(nil),          // 22: model.Message
	(*model.Session)(nil),          // 23: model.Session
	(*model.Task)(nil),             // 24: model.Task
	(*model.Agent)(nil),            // 25: model.Agent
	(*model.MCPServer)(nil),        // 26: model.MCPServer
	(*model.Base)(nil),             // 27: model.Base
}
var file_api_proto_service_proto_depIdxs = []int32{
	21, // 0: service.ListProjectsResponse.projects:type_name -> model.Project
	22, // 1: service.ListMessagesResponse.messages:type_name -> model.Message
	23, // 2: service.ListSessionsResponse.sessions:type_name -> model.Session
	24, // 3: service.ListTasksResponse.tasks:type_name -> model.Task
	25, // 4: service.ListAgentsResponse.agents:type_name -> model.Agent
	26, // 5: service.ListMCPServersResponse.servers:type_name -> model.MCPServer
	20, // 6: service.ListMCPToolsResponse.tools:type_name -> service.ToolInfo
	2,  // 7: service.ProjectService.CreateProject:input_type -> service.CreateProjectRequest
	3,  // 8: service.ProjectService.UpdateProject:input_type -> service.UpdateProjectRequest
	1,  // 9: service.ProjectService.DeleteProject:input_type -> service.IDRequest
	0,  // 10: service.ProjectService.ListProjects:input_type -> service.Empty
	1,  // 11: service.ProjectService.GetProject:input_type -> service.IDRequest
	5,  // 12: service.ChatService.Chat:input_type -> service.ChatRequest
	1,  // 13: service.ChatService.ListMessages:input_type -> service.IDRequest
	1,  // 14: service.ChatService.ClearMessages:input_type -> service.IDRequest
	8,  // 15: service.ChatService.CreateSession:input_type -> service.CreateSessionRequest
	1,  // 16: service.ChatService.ListSessions:input_type -> service.IDRequest
	1,  // 17: service.ChatService.DeleteSession:input_type -> service.IDRequest
	10, // 18: service.TaskService.CreateTask:input_type -> service.CreateTaskRequest
	11, // 19: service.TaskService.UpdateTask:input_type -> service.UpdateTaskRequest
	1,  // 20: service.TaskService.DeleteTask:input_type -> service.IDRequest
	1,  // 21: service.TaskService.ListTasks:input_type -> service.IDRequest
	13, // 22: service.AgentService.CreateAgent:input_type -> service.CreateAgentRequest
	14, // 23: service.AgentService.UpdateAgent:input_type -> service.UpdateAgentRequest
	1,  // 24: service.AgentService.DeleteAgent:input_type -> service.IDRequest
	0,  // 25: service.AgentService.ListAgents:input_type -> service.Empty
	16, // 26: service.MCPService.CreateMCPServer:input_type -> service.CreateMCPServerRequest
	17, // 27: service.MCPService.UpdateMCPServer:input_type -> service.UpdateMCPServerRequest
	1,  // 28: service.MCPService.DeleteMCPServer:input_type -> service.IDRequest
	0,  // 29: service.MCPService.ListMCPServers:input_type -> service.Empty
	1,  // 30: service.MCPService.ListMCPTools:input_type -> service.IDRequest
	27, // 31: service.ProjectService.CreateProject:output_type -> model.Base
	27, // 32: service.ProjectService.UpdateProject:output_type -> model.Base
	0,  // 33: service.ProjectService.DeleteProject:output_type -> service.Empty
	4,  // 34: service.ProjectService.ListProjects:output_type -> service.ListProjectsResponse
	21, // 35: service.ProjectService.GetProject:output_type -> model.Project
	6,  // 36: service.ChatService.Chat:output_type -> service.ChatEvent
	7,  // 37: service.ChatService.ListMessages:output_type -> service.ListMessagesResponse
	0,  // 38: service.ChatService.ClearMessages:output_type -> service.Empty
	27, // 39: service.ChatService.CreateSession:output_type -> model.Base
	9,  // 40: service.ChatService.ListSessions:output_type -> service.ListSessionsResponse
	0,  // 41: service.ChatService.DeleteSession:output_type -> service.Empty
	24, // 42: service.TaskService.CreateTask:output_type -> model.Task
	0,  // 43: service.TaskService.UpdateTask:output_type -> service.Empty
	0,  // 44: service.TaskService.DeleteTask:output_type -> service.Empty
	12, // 45: service.TaskService.ListTasks:output_type -> service.ListTasksResponse
	27, // 46: service.AgentService.CreateAgent:output_type -> model.Base
	27, // 47: service.AgentService.UpdateAgent:output_type -> model.Base
	0,  // 48: service.AgentService.DeleteAgent:output_type -> service.Empty
	15, // 49: service.AgentService.ListAgents:output_type -> service.ListAgentsResponse
	27, // 50: service.MCPService.CreateMCPServer:output_type -> model.Base
	27, // 51: service.MCPService.UpdateMCPServer:output_type -> model.Base
	0,  // 52: service.MCPService.DeleteMCPServer:output_type -> service.Empty
	18, // 53: service.MCPService.ListMCPServers:output_type -> service.ListMCPServersResponse
	19, // 54: service.MCPService.ListMCPTools:output_type -> service.ListMCPToolsResponse
	31, // [31:55] is the sub-list for method output_type
	7,  // [7:31] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_proto_service_proto_init() }
func file_api_proto_service_proto_init() {
	if File_api_proto_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_service_proto_rawDesc), len(file_api_proto_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_api_proto_service_proto_goTypes,
		DependencyIndexes: file_api_proto_service_proto_depIdxs,
		MessageInfos:      file_api_proto_service_proto_msgTypes,
	}.Build()
	File_api_proto_service_proto = out.File
	file_api_proto_service_proto_goTypes = nil
	file_api_proto_service_proto_depIdxs = nil
}
