// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.1
// source: api/proto/model.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Base struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Base) Reset() {
	*x = Base{}
	mi := &file_api_proto_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Base) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Base) ProtoMessage() {}

func (x *Base) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Base.ProtoReflect.Descriptor instead.
func (*Base) Descriptor() ([]byte, []int) {
	return file_api_proto_model_proto_rawDescGZIP(), []int{0}
}

func (x *Base) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Base) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Base) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *Base                  `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_api_proto_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_api_proto_model_proto_rawDescGZIP(), []int{1}
}

func (x *Project) GetBase() *Base {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Project) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *Base                  `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	ProjectId     uint32                 `protobuf:"varint,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	AgentId       uint32                 `protobuf:"varint,4,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_api_proto_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_api_proto_model_proto_rawDescGZIP(), []int{2}
}

func (x *Session) GetBase() *Base {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *Session) GetProjectId() uint32 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *Session) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Session) GetAgentId() uint32 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *Base                  `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	SessionId     uint32                 `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"` // user, assistant, system, tool
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"` // text, image, tool_use, tool_result
	ToolCallId    string                 `protobuf:"bytes,6,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_api_proto_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_api_proto_model_proto_rawDescGZIP(), []int{3}
}

func (x *Message) GetBase() *Base {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *Message) GetSessionId() uint32 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Message) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *Base                  `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	SessionId     uint32                 `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ParentId      uint32                 `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"` // optional, 0 if null
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`     // pending, in_progress, completed, failed
	Priority      string                 `protobuf:"bytes,6,opt,name=priority,proto3" json:"priority,omitempty"` // high, medium, low
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_api_proto_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_api_proto_model_proto_rawDescGZIP(), []int{4}
}

func (x *Task) GetBase() *Base {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *Task) GetSessionId() uint32 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *Task) GetParentId() uint32 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *Task) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Task) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Task) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

type Agent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *Base                  `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	SystemPrompt  string                 `protobuf:"bytes,4,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	ModelId       uint32                 `protobuf:"varint,5,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	ModeId        uint32                 `protobuf:"varint,6,opt,name=mode_id,json=modeId,proto3" json:"mode_id,omitempty"`
	Tools         []*Tool                `protobuf:"bytes,7,rep,name=tools,proto3" json:"tools,omitempty"`
	McpServers    []*MCPServer           `protobuf:"bytes,8,rep,name=mcp_servers,json=mcpServers,proto3" json:"mcp_servers,omitempty"`
	Type          string                 `protobuf:"bytes,9,opt,name=type,proto3" json:"type,omitempty"` // builtin, custom
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Agent) Reset() {
	*x = Agent{}
	mi := &file_api_proto_model_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_model_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_api_proto_model_proto_rawDescGZIP(), []int{5}
}

func (x *Agent) GetBase() *Base {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *Agent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Agent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Agent) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *Agent) GetModelId() uint32 {
	if x != nil {
		return x.ModelId
	}
	return 0
}

func (x *Agent) GetModeId() uint32 {
	if x != nil {
		return x.ModeId
	}
	return 0
}

func (x *Agent) GetTools() []*Tool {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *Agent) GetMcpServers() []*MCPServer {
	if x != nil {
		return x.McpServers
	}
	return nil
}

func (x *Agent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type Tool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *Base                  `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`             // builtin, script, custom
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`       // script content or other config
	Parameters    string                 `protobuf:"bytes,6,opt,name=parameters,proto3" json:"parameters,omitempty"` // JSON schema string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tool) Reset() {
	*x = Tool{}
	mi := &file_api_proto_model_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tool) ProtoMessage() {}

func (x *Tool) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_model_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tool.ProtoReflect.Descriptor instead.
func (*Tool) Descriptor() ([]byte, []int) {
	return file_api_proto_model_proto_rawDescGZIP(), []int{6}
}

func (x *Tool) GetBase() *Base {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *Tool) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tool) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Tool) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Tool) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Tool) GetParameters() string {
	if x != nil {
		return x.Parameters
	}
	return ""
}

type MCPServer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *Base                  `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"` // stdio, sse
	Command       string                 `protobuf:"bytes,5,opt,name=command,proto3" json:"command,omitempty"`
	Args          string                 `protobuf:"bytes,6,opt,name=args,proto3" json:"args,omitempty"`
	Env           string                 `protobuf:"bytes,7,opt,name=env,proto3" json:"env,omitempty"`
	Url           string                 `protobuf:"bytes,8,opt,name=url,proto3" json:"url,omitempty"`
	Enabled       bool                   `protobuf:"varint,9,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPServer) Reset() {
	*x = MCPServer{}
	mi := &file_api_proto_model_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPServer) ProtoMessage() {}

func (x *MCPServer) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_model_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPServer.ProtoReflect.Descriptor instead.
func (*MCPServer) Descriptor() ([]byte, []int) {
	return file_api_proto_model_proto_rawDescGZIP(), []int{7}
}

func (x *MCPServer) GetBase() *Base {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *MCPServer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MCPServer) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MCPServer) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MCPServer) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *MCPServer) GetArgs() string {
	if x != nil {
		return x.Args
	}
	return ""
}

func (x *MCPServer) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *MCPServer) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *MCPServer) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type AIModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *Base                  `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Provider      string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	BaseUrl       string                 `protobuf:"bytes,4,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	ApiKey        string                 `protobuf:"bytes,5,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	ConfigJson    string                 `protobuf:"bytes,6,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	IsDefault     bool                   `protobuf:"varint,7,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIModel) Reset() {
	*x = AIModel{}
	mi := &file_api_proto_model_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIModel) ProtoMessage() {}

func (x *AIModel) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_model_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIModel.ProtoReflect.Descriptor instead.
func (*AIModel) Descriptor() ([]byte, []int) {
	return file_api_proto_model_proto_rawDescGZIP(), []int{8}
}

func (x *AIModel) GetBase() *Base {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *AIModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AIModel) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *AIModel) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *AIModel) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *AIModel) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

func (x *AIModel) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

type Mode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *Base                  `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mode) Reset() {
	*x = Mode{}
	mi := &file_api_proto_model_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mode) ProtoMessage() {}

func (x *Mode) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_model_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mode.ProtoReflect.Descriptor instead.
func (*Mode) Descriptor() ([]byte, []int) {
	return file_api_proto_model_proto_rawDescGZIP(), []int{9}
}

func (x *Mode) GetBase() *Base {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *Mode) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Mode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Mode) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_api_proto_model_proto protoreflect.FileDescriptor

const file_api_proto_model_proto_rawDesc = "" +
	"\n" +
	"\x15api/proto/model.proto\x12\x05model\"T\n" +
	"\x04Base\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\tR\tupdatedAt\"t\n" +
	"\aProject\x12\x1f\n" +
	"\x04base\x18\x01 \x01(\v2\v.model.BaseR\x04base\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\"x\n" +
	"\aSession\x12\x1f\n" +
	"\x04base\x18\x01 \x01(\v2\v.model.BaseR\x04base\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\rR\tprojectId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x19\n" +
	"\bagent_id\x18\x04 \x01(\rR\aagentId\"\xad\x01\n" +
	"\aMessage\x12\x1f\n" +
	"\x04base\x18\x01 \x01(\v2\v.model.BaseR\x04base\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\rR\tsessionId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12 \n" +
	"\ftool_call_id\x18\x06 \x01(\tR\n" +
	"toolCallId\"\xb1\x01\n" +
	"\x04Task\x12\x1f\n" +
	"\x04base\x18\x01 \x01(\v2\v.model.BaseR\x04base\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\rR\tsessionId\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\rR\bparentId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\tR\bpriority\"\xa1\x02\n" +
	"\x05Agent\x12\x1f\n" +
	"\x04base\x18\x01 \x01(\v2\v.model.BaseR\x04base\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12#\n" +
	"\rsystem_prompt\x18\x04 \x01(\tR\fsystemPrompt\x12\x19\n" +
	"\bmodel_id\x18\x05 \x01(\rR\amodelId\x12\x17\n" +
	"\amode_id\x18\x06 \x01(\rR\x06modeId\x12!\n" +
	"\x05tools\x18\a \x03(\v2\v.model.ToolR\x05tools\x121\n" +
	"\vmcp_servers\x18\b \x03(\v2\x10.model.MCPServerR\n" +
	"mcpServers\x12\x12\n" +
	"\x04type\x18\t \x01(\tR\x04type\"\xab\x01\n" +
	"\x04Tool\x12\x1f\n" +
	"\x04base\x18\x01 \x01(\v2\v.model.BaseR\x04base\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1e\n" +
	"\n" +
	"parameters\x18\x06 \x01(\tR\n" +
	"parameters\"\xe2\x01\n" +
	"\tMCPServer\x12\x1f\n" +
	"\x04base\x18\x01 \x01(\v2\v.model.BaseR\x04base\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x18\n" +
	"\acommand\x18\x05 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x06 \x01(\tR\x04args\x12\x10\n" +
	"\x03env\x18\a \x01(\tR\x03env\x12\x10\n" +
	"\x03url\x18\b \x01(\tR\x03url\x12\x18\n" +
	"\aenabled\x18\t \x01(\bR\aenabled\"\xce\x01\n" +
	"\aAIModel\x12\x1f\n" +
	"\x04base\x18\x01 \x01(\v2\v.model.BaseR\x04base\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12\x19\n" +
	"\bbase_url\x18\x04 \x01(\tR\abaseUrl\x12\x17\n" +
	"\aapi_key\x18\x05 \x01(\tR\x06apiKey\x12\x1f\n" +
	"\vconfig_json\x18\x06 \x01(\tR\n" +
	"configJson\x12\x1d\n" +
	"\n" +
	"is_default\x18\a \x01(\bR\tisDefault\"o\n" +
	"\x04Mode\x12\x1f\n" +
	"\x04base\x18\x01 \x01(\v2\v.model.BaseR\x04base\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescriptionB\x12Z\x10iat/pkg/pb/modelb\x06proto3"

var (
	file_api_proto_model_proto_rawDescOnce sync.Once
	file_api_proto_model_proto_rawDescData []byte
)

func file_api_proto_model_proto_rawDescGZIP() []byte {
	file_api_proto_model_proto_rawDescOnce.Do(func() {
		file_api_proto_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_model_proto_rawDesc), len(file_api_proto_model_proto_rawDesc)))
	})
	return file_api_proto_model_proto_rawDescData
}

var file_api_proto_model_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_proto_model_proto_goTypes = []any{
	(*Base)(nil),      // 0: model.Base
	(*Project)(nil),   // 1: model.Project
	(*Session)(nil),   // 2: model.Session
	(*Message)(nil),   // 3: model.Message
	(*Task)(nil),      // 4: model.Task
	(*Agent)(nil),     // 5: model.Agent
	(*Tool)(nil),      // 6: model.Tool
	(*MCPServer)(nil), // 7: model.MCPServer
	(*AIModel)(nil),   // 8: model.AIModel
	(*Mode)(nil),      // 9: model.Mode
}
var file_api_proto_model_proto_depIdxs = []int32{
	0,  // 0: model.Project.base:type_name -> model.Base
	0,  // 1: model.Session.base:type_name -> model.Base
	0,  // 2: model.Message.base:type_name -> model.Base
	0,  // 3: model.Task.base:type_name -> model.Base
	0,  // 4: model.Agent.base:type_name -> model.Base
	6,  // 5: model.Agent.tools:type_name -> model.Tool
	7,  // 6: model.Agent.mcp_servers:type_name -> model.MCPServer
	0,  // 7: model.Tool.base:type_name -> model.Base
	0,  // 8: model.MCPServer.base:type_name -> model.Base
	0,  // 9: model.AIModel.base:type_name -> model.Base
	0,  // 10: model.Mode.base:type_name -> model.Base
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_api_proto_model_proto_init() }
func file_api_proto_model_proto_init() {
	if File_api_proto_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_model_proto_rawDesc), len(file_api_proto_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_model_proto_goTypes,
		DependencyIndexes: file_api_proto_model_proto_depIdxs,
		MessageInfos:      file_api_proto_model_proto_msgTypes,
	}.Build()
	File_api_proto_model_proto = out.File
	file_api_proto_model_proto_goTypes = nil
	file_api_proto_model_proto_depIdxs = nil
}
