// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {common} from '../models';

export function CreateAIModel(arg1:model.AIModel):Promise<common.Result>;

export function CreateProject(arg1:string,arg2:string):Promise<common.Result>;

export function CreateSession(arg1:number,arg2:string):Promise<common.Result>;

export function DeleteAIModel(arg1:number):Promise<common.Result>;

export function DeleteProject(arg1:number):Promise<common.Result>;

export function DeleteSession(arg1:number):Promise<common.Result>;

export function Greet(arg1:string):Promise<string>;

export function ListAIModels():Promise<common.Result>;

export function ListProjects():Promise<common.Result>;

export function ListSessions(arg1:number):Promise<common.Result>;

export function TestAIModel(arg1:model.AIModel):Promise<common.Result>;
