// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAIModel(arg1) {
  return window['go']['main']['App']['CreateAIModel'](arg1);
}

export function CreateProject(arg1, arg2) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2);
}

export function CreateSession(arg1, arg2) {
  return window['go']['main']['App']['CreateSession'](arg1, arg2);
}

export function DeleteAIModel(arg1) {
  return window['go']['main']['App']['DeleteAIModel'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListAIModels() {
  return window['go']['main']['App']['ListAIModels']();
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ListSessions(arg1) {
  return window['go']['main']['App']['ListSessions'](arg1);
}

export function TestAIModel(arg1) {
  return window['go']['main']['App']['TestAIModel'](arg1);
}

export function UpdateProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateProject'](arg1, arg2, arg3);
}
