// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {common} from '../models';

export function CreateAIModel(arg1:model.AIModel):Promise<common.Result>;

export function CreateAgent(arg1:string,arg2:string,arg3:string,arg4:number,arg5:Array<number>):Promise<common.Result>;

export function CreateProject(arg1:string,arg2:string):Promise<common.Result>;

export function CreateScript(arg1:string,arg2:string,arg3:string):Promise<common.Result>;

export function CreateSession(arg1:number,arg2:string,arg3:number):Promise<common.Result>;

export function CreateTool(arg1:model.Tool):Promise<common.Result>;

export function DeleteAIModel(arg1:number):Promise<common.Result>;

export function DeleteAgent(arg1:number):Promise<common.Result>;

export function DeleteProject(arg1:number):Promise<common.Result>;

export function DeleteScript(arg1:number):Promise<common.Result>;

export function DeleteSession(arg1:number):Promise<common.Result>;

export function DeleteTool(arg1:number):Promise<common.Result>;

export function Greet(arg1:string):Promise<string>;

export function ListAIModels():Promise<common.Result>;

export function ListAgents():Promise<common.Result>;

export function ListMessages(arg1:number):Promise<common.Result>;

export function ListProjects():Promise<common.Result>;

export function ListScripts():Promise<common.Result>;

export function ListSessions(arg1:number):Promise<common.Result>;

export function ListTools():Promise<common.Result>;

export function RunScript(arg1:number):Promise<common.Result>;

export function SendMessage(arg1:number,arg2:string,arg3:number):Promise<common.Result>;

export function TestAIModel(arg1:model.AIModel):Promise<common.Result>;

export function UpdateAgent(arg1:number,arg2:string,arg3:string,arg4:string,arg5:number,arg6:Array<number>):Promise<common.Result>;

export function UpdateProject(arg1:number,arg2:string,arg3:string):Promise<common.Result>;

export function UpdateScript(arg1:number,arg2:string,arg3:string,arg4:string):Promise<common.Result>;

export function UpdateTool(arg1:model.Tool):Promise<common.Result>;
