// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {result} from '../models';

export function CreateAIModel(arg1:model.AIModel):Promise<result.Result>;

export function CreateAgent(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:number,arg9:Array<number>,arg10:Array<number>,arg11:number,arg12:string,arg13:string):Promise<result.Result>;

export function CreateMCPServer(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<result.Result>;

export function CreateProject(arg1:string,arg2:string,arg3:string):Promise<result.Result>;

export function CreateSession(arg1:string,arg2:number,arg3:number):Promise<result.Result>;

export function CreateTool(arg1:model.Tool):Promise<result.Result>;

export function DeleteAIModel(arg1:number):Promise<result.Result>;

export function DeleteAgent(arg1:number):Promise<result.Result>;

export function DeleteMCPServer(arg1:number):Promise<result.Result>;

export function DeleteProject(arg1:number):Promise<result.Result>;

export function DeleteSession(arg1:number):Promise<result.Result>;

export function DeleteTool(arg1:number):Promise<result.Result>;

export function GetScriptAPIDocs():Promise<result.Result>;

export function GetSessionMessages(arg1:number):Promise<result.Result>;

export function IndexAllProjects():Promise<result.Result>;

export function IndexProject(arg1:number):Promise<result.Result>;

export function ListAIModels():Promise<result.Result>;

export function ListAgents():Promise<result.Result>;

export function ListMCPServers():Promise<result.Result>;

export function ListMCPTools(arg1:number):Promise<result.Result>;

export function ListModes():Promise<result.Result>;

export function ListProjects():Promise<result.Result>;

export function ListSessions(arg1:number):Promise<result.Result>;

export function ListTools():Promise<result.Result>;

export function SelectDirectory():Promise<result.Result>;

export function TestAIModel(arg1:model.AIModel):Promise<result.Result>;

export function UpdateAgent(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:number,arg10:Array<number>,arg11:Array<number>,arg12:number,arg13:string,arg14:string):Promise<result.Result>;

export function UpdateMCPServer(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:boolean):Promise<result.Result>;

export function UpdateProject(arg1:number,arg2:string,arg3:string,arg4:string):Promise<result.Result>;

export function UpdateSession(arg1:number,arg2:string):Promise<result.Result>;

export function UpdateTool(arg1:model.Tool):Promise<result.Result>;
